### ISSUE TITLE
Add context menuitem for tabs

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#2]
Can you add a context menuitem when right-clicking on any tab to perform the copy action?  That way, the toolbar will need one less button.

**Comment by 0xfeeddeadbeef** [comment]
Thanks for suggestion, @Gitoffthelawn!

Turns out, that Google Chrome does not support adding menu items to the Tab-level context menu. I've added it at the Page-level as a workaround (Reference: [contextMenus ContextType](https://developers.chrome.com/extensions/contextMenus#type-ContextType) does not list `tab`):

![image](https://user-images.githubusercontent.com/732366/33272377-6e2acd52-d3a3-11e7-9f34-c0bbff5fe5b1.png)

Mozilla Firefox works fine, — `tab` ContextType is supported:

![image](https://user-images.githubusercontent.com/732366/33272521-d1c4eb4a-d3a3-11e7-801d-f2fad5c27f66.png)

**Comment by Gitoffthelawn** [comment]
Thank you!  That works perfectly!  Love it!
